---
title: "Análisis multinivel del estatus social subjetivo: el caso de la Región Metropolitana"
subtitle: "Análisis de Datos Multinivel"
author: "Cristóbal Mejías, Nicolás Outerbridge y Victoria Arias"
date: "28/06/2025"
lang: es
format: html
editor: visual
---

```{css, echo = FALSE}
.justify {
  text-align: justify !important
}
```

# Abstract

# Introducción

# Objetivos

# Variables

Podemos cargar las librerías sin que aparezca en nuestro informe, señalando la especificación al chunk `echo=FALSE`.

```{r librerias, echo=FALSE, warning=FALSE, message=FALSE, collapse=TRUE}
library(pacman)
pacman::p_load(tidyverse,   
               sjPlot,      
               confintr,    
               gginference,  
               rempsyc,     
               broom,       
               sjmisc,       
               knitr,
               lme4,
               reghelper,
               haven,
               stargazer,
               ggplot2, 
               texreg, 
               dplyr,
               summarytools,
               gt)            

options(scipen = 999) # para desactivar notacion cientifica
rm(list = ls()) # para limpiar el entorno de trabajo
```

Esto lo podemos repetir para la carga de la base de datos y el procesamiento de los datos.

```{r datos, echo=FALSE, warning=FALSE, message=FALSE}
load(file="output/data.RData")
```

```{r variables, echo=FALSE, warning=FALSE, message=FALSE}
tabla <- tribble(
  ~Tipo, ~Variable, ~Operacionalización,
  
  "Dependiente", "Estatus social subjetivo (d01_02)", 
  "Hay grupos que tienden a ubicarse en los niveles más altos y otros en los más bajos\n¿Dónde se ubicaría usted?\n1 (Nivel más bajo) – 10 (Nivel más alto)",
  
  "Nivel 1", "Estatus social familiar (d01_02)", 
  "Pensando en la familia en donde usted creció\n¿Dónde se ubicaría en esta escala?\n1 (Nivel más bajo) – 10 (Nivel más alto)",
  
  "", "Nivel educativo (m01)", 
  "Educación básica incompleta\nEducación básica completa\nEducación media incompleta\nEducación media completa\nEducación superior no universitaria\nEducación universitaria completa",
  
  "", "Ingreso (m14)", 
  "",
  
  "Nivel 2", "Percepción de seguridad", 
  "",
  
  "", "Cohesión social", 
  "",
  
  "", "Pobreza multidimensional", 
  ""
)


tabla %>%
  gt() %>%
  tab_header(
    title = md("**Tabla 2: Variables del estudio**")
  ) %>%
  cols_label(
    Tipo = "Tipo",
    Variable = "Variable",
    Operacionalización = "Operacionalización"
  ) %>%
  tab_style(
    style = cell_text(weight = "bold"),
    locations = cells_body(
      columns = Tipo,
      rows = Tipo != ""
    )
  ) %>%
  tab_options(
    table.font.size = px(13),
    row.striping.include_table_body = TRUE
  )

```

# Resultados

# Conclusiones

# Bibliografía
